---
sudo: required

services:
  - docker

env:
  - distribution: debian
    version: jessie
  - distribution: debian
    version: wheezy
  - distribution: debian
    version: stretch

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-motd:ro ${distribution}-${version}:ansible > "${container_id}"'
  # syntax check
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-motd/tests/test.yml --syntax-check'
  # role execution
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-motd/tests/test.yml'
  # print MOTD
  - 'sudo docker exec "$(cat ${container_id})" /etc/update-motd.d/00-header'
  - 'sudo docker exec "$(cat ${container_id})" /etc/update-motd.d/10-hostname'
  - 'sudo docker exec "$(cat ${container_id})" /etc/update-motd.d/40-kernel'
  - 'sudo docker exec "$(cat ${container_id})" /etc/update-motd.d/50-specs'
  - 'sudo docker exec "$(cat ${container_id})" /etc/update-motd.d/90-footer'

notifications:
  # Notify Ansible Galaxy when a role builds successfully.
