FROM debian:wheezy

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    software-properties-common \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    git \
 && rm -rf /var/lib/apt/lists/*

RUN pip install -v ansible -i https://pypi.python.org/simple/

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

RUN mkdir -p /etc/pam.d && echo "motd=/run/motd.dynamic" > /etc/pam.d/sshd

ENTRYPOINT ["/sbin/init"]
